### ISSUE TITLE
Needs update for WotLK? 

### ISSUE THREAD

**Issue by enoxitus** [axlroden/stayin#1]
Hey, love the project! Worked fine, until I needed to reconnect. I tested it by disconnecting from internet, and it didn't notice or recognize the DC. 
Could be an issue on my end, not sure. 
But if you can fix it, that'd be great!

**Comment by axlroden** [comment]
I havn't updated screenshots for wotlk, will probably get around to it before launch.. (I don't have queues atm)

**Comment by enoxitus** [comment]
> I havn't updated screenshots for wotlk, will probably get around to it before launch.. (I don't have queues atm)

no worries, I managed to sorta fix it myself by just changing the images and running the python script (not sure how the packing into .exe works)

**Comment by axlroden** [comment]
I just released a new version..

**Comment by enoxitus** [comment]
oh thank you
