### ISSUE TITLE
Script button detection problem (?)

### ISSUE THREAD

**Issue by CodenameNoliP** [axlroden/stayin#2]
Tried to use your script. When trying to launch the game cursor points couple pixels below button.
![2nMlumM](https://user-images.githubusercontent.com/34750344/189799761-653728ba-50ba-4249-9e24-31ed1dd2164b.png)

**Comment by CodenameNoliP** [comment]
I did some funny stuff with the coordinates you used and it works (added some digits to y).

**Comment by axlroden** [comment]
I tried with a lot of resizing, and the pixels I click at fit on anything I tested on, you have a weird resize of your battle.net window ?

**Comment by CodenameNoliP** [comment]
> I tried with a lot of resizing, and the pixels I click at fit on anything I tested on, you have a weird resize of your battle.net window ?

If you mean on default window size, the program opens b.net by itself and it is always either fullscreen or small window on left side of monitor. I've tied disconnecting second monitor and changing resolution.

If there is any other way to resize battle.net window let me know so I can check.

**Comment by axlroden** [comment]
just open it and resize it.. without the program.. everything has to run on your primary monitor.

**Comment by CodenameNoliP** [comment]
> just open it and resize it.. without the program.. everything has to run on your primary monitor.

No matter how located/resized window is it stills finds this one spot below button.

**Comment by axlroden** [comment]
are you running 1080p/1440p/4k monitor?

**Comment by CodenameNoliP** [comment]
1440p and program outputs that it recognizes my resolution (1440p)

**Comment by axlroden** [comment]
also check your windows scaling, if its too big it might change location of button.

**Comment by axlroden** [comment]
I just tried with 125% scaling and it misses, change your scaling to 100%.

**Comment by CodenameNoliP** [comment]
Windows Scale is set to 100%
![obraz](https://user-images.githubusercontent.com/34750344/189989886-62104c7c-ef6f-48cd-83f3-58aa36d9170f.png)

**Comment by axlroden** [comment]
i dunno your running some other scaling than normal, i've adjusted the click a bit up, should not ruin it for others.
