### ISSUE TITLE
Reconnect after dc and server maintance feature

### ISSUE THREAD

**Issue by CodenameNoliP** [axlroden/stayin#4]
This stuff works miracles but as for now servers tend to kick often (also Battle.net loses connection) so I wonder if there would be a chance of including such a feature. 
Also would be nice for the program to understand servers being offline or if the whole PC loses internet connection for a bit, In a way that it tries to reconnect using a button, or refresh realm selection.

**Comment by axlroden** [comment]
No. This does not do anything ingame to avoid getting banned. If it can't figure out whats going on it will kill wow and start over.
